In [ ]:
import numpy as np

In [ ]:
# 배열 생성하는 법 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([[1,2,3,4,5]])

#arr1은 1차원 데이터 이지만 
print('arr1 shape: ', arr1.shape)
print('arr2 shape: ', arr2.shape)
#arr2는 2차원 데이터이다. 이는 데이터의 개수는 다르지만 명백히 차원이 다른 데이터임으로 유의해야한다.
print('arr3 shape: ', arr3.shape)

print('arr1 ndim: ',arr1.ndim)
print('arr3 ndim: ',arr3.ndim)

arr1 shape:  (5,)
arr2 shape:  (2, 4)
arr3 shape:  (1, 5)
arr1 ndim:  1
arr3 ndim:  2


In [ ]:
#ndarray에서는 오직 일관된 하나의 데이터형만 가지고 배열을 만들수 있다.
list1 = [1,2,3,4]
print('list1 =',list1)
print('list type: ',type(list1))
arr1 = np.array(list1)
print('ndarray type: ', type(arr1))
print('ndarray dtype: ', arr1.dtype)

print('='*40)
# 파이썬 리스트에서는 여러 종류의 서로다른 데이터 타입이 리스트의 원소가 될 수 있다.
list2 = [1,2,3, "true"]
print('list2 =', list2)
# ndarray에서는 리스트에 있는 여러 데이터형 중에서 가장 크기 큰 데이터를 기준으로 일괄적인 타입 변경이 진행된다.
arr2 = np.array(list2)
print('arr2: ', arr2)
print('arr2 elements: ', arr2)
print('arr2 dtype', arr2.dtype)

print('='*40)
#float와 int 중 float가 크기 때문에 ndarray에서는 float로 dtype이 정해진다.
list3 = [1,2,3,4.0]
print('list3: ', list3)
arr3 = np.array(list3);
print('arr3: ', arr3)
print('arr3 elements: ', arr3)
print('arr3 dtype: ', arr3.dtype)

list1 = [1, 2, 3, 4]
list type:  <class 'list'>
ndarray type:  <class 'numpy.ndarray'>
ndarray dtype:  int64
list2 = [1, 2, 3, 'true']
arr2:  ['1' '2' '3' 'true']
arr2 elements:  ['1' '2' '3' 'true']
arr2 dtype <U21
list3:  [1, 2, 3, 4.0]
arr3:  [1. 2. 3. 4.]
arr3 elements:  [1. 2. 3. 4.]
arr3 dtype:  float64


In [ ]:
# 타입 변경하는 법
list1 = [1,2,3,4,5,6.0]
ndarray1 = np.array(list1)

print('ndarray1 dtype: ',ndarray1.dtype)
# 기존의 배열은 그대로 있고 반환값으로 배열이 나온다는 것을 기억해야한다.
ndarray1 = ndarray1.astype('int64')
print('ndarray1 dtype: ', ndarray1.dtype);
# int64 -> int32
ndarray1 = ndarray1.astype('int32')
print('ndarray1 dtype: ', ndarray1.dtype);

ndarray1 dtype:  float64
ndarray1 dtype:  int64
ndarray1 dtype:  int32


In [ ]:
# ndarray를 편하게 생성하는 방법
sequence_arr = np.arange(10)
print('np.arange(10): ',sequence_arr)
print('dtype: ', sequence_arr.dtype, '/shape: ', sequence_arr.shape, '/ndim: ', sequence_arr.ndim)


np.arange(10):  [0 1 2 3 4 5 6 7 8 9]
dtype:  int64 /shape:  (10,) /ndim:  1


In [ ]:
# 특정 값으로 초기화된 배열 생성
arr = np.ones((3,2), dtype = 'int32')
print("np.ones.((3,2),dtype = 'int32')\n", arr)
print('dtype: ', arr.dtype, '/ndim: ', arr.ndim, '/shape: ', arr.shape)
print("="*40)
# dtype을 지정해주지 않으면 default로 float64로 지정된다.
arr = np.zeros((3,2))
print("np.zeros((3,2))\n", arr)
print('dtype: ', arr.dtype, '/ndim: ', arr.ndim, '/shape: ', arr.shape)

np.ones.((3,2),dtype = 'int32')
 [[1 1]
 [1 1]
 [1 1]]
dtype:  int32 /ndim:  2 /shape:  (3, 2)
np.zeros((3,2))
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
dtype:  float64 /ndim:  2 /shape:  (3, 2)


In [ ]:
# 배열의 형태를 변경하는 메소드 reshape
arr =  np.arange(10)
print('arr:\n', arr)
arr = arr.reshape(2,5)
print('arr:\n', arr)
arr = arr.reshape(5,2)
print('arr:\n', arr)
# 처음이랑 데이터의 개수는 같지만 데이터의 형태는 1차원 데이터 구조에서 2차원 형태의 데이터가 되었다.
arr = arr.reshape(1,10)
print('arr:\n', arr)

arr:
 [0 1 2 3 4 5 6 7 8 9]
arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arr:
 [[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
# reshape를 혁신적이고 효율적으로 사용하는 법
arr = np.arange(10)
# 인자로 -1을 입력 받으면 해당 숫자에는 현재 데이터가 만들 수 있는 형태를 고려하여 자동으로 만든다
# 아래의 경우에는 전체 데이터의 개수가 10개 임으로 -1자리에는 10이 들어간다.
print(arr.reshape(-1,1))
print("="*20)
# -1에 2
print(arr.reshape(5,-1))
print("="*20)
# -1에 5
print(arr.reshape(-1,5))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 데이터 세트 선택하기 
# 특정 데이터만 추출
