<a href="https://colab.research.google.com/github/Tianea2160/PythonPractice/blob/master/sklearnPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install scikit-learn

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [ ]:
import pandas as pd

iris = load_iris()

iris_data = iris.data
# print("iris data type : ", type(iris.data))
# print("iris data : ", iris.data)

iris_label = iris.target
print('iris target value : ', iris_label)
print('iris target name : ', iris.target_names)

iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)


iris target value :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target name :  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0

[3 rows x 5 columns]

In [ ]:
# test, train case split

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [ ]:
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [ ]:
result = dt_clf.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, result)

SyntaxError: ignored

In [ ]:
# 학습데이터로 test까지 해보기
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score 
iris_data = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris_data.data
train_label = iris_data.target

dt_clf.fit(train_data, train_label)
pred = dt_clf.predict(train_data)
print(accuracy_score(pred, train_label))


1.0


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

iris_data = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

dt_clf = DecisionTreeClassifier()
dt_clf.fit(x_train, y_train)
pred = dt_clf.predict(x_test)
print(accuracy_score(pred, y_test))

0.9555555555555556


In [ ]:
# kfold 방식을 사용하여 학습
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
import numpy as np

iris_data = load_iris()
features = iris_data.data
label = iris_data.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits = 5)
arr_accuracy = []
print("붓꽃 데이터 세트 크기 : ", features.shape[0])

n_iter = 0
for train_index, test_index in kfold.split(features):
  x_train, x_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)
  pred = dt_clf.predict(x_test)
  n_iter+=1
  accuracy = np.round(accuracy_score(pred, y_test),4)
  train_size = x_train.shape[0]
  test_size = x_test.shape[0]

  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter, accuracy, train_size, test_size))
  # print("#{0}검증 세트 인덱스:{1}".format(n_iter, test_index)))
  print(test_index)
  arr_accuracy.append(accuracy)
print("평균 검증 정확도:", np.mean(arr_accuracy))

붓꽃 데이터 세트 크기 :  150

#1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도: 0.9


In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

iris_df['label'] = iris.target
print(iris_df['label'].value_counts())

# kfold를 사용하면 데이터 세트 분할 과정에서 고르지 못한 세트 분할이 일어날 수 있다(중요)

2    50
1    50
0    50
Name: label, dtype: int64


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
import pandas as pd

# 좋지 않은 예시
kfold = KFold(n_splits=3)
n_iter = 0;
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target


for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print("## 교차 검증:{0}".format(n_iter))
  print('train 레이블 데이터 분포 : ')
  print(label_train.value_counts())
  print('test 레이블 데이터 분포 : ')
  print(label_test.value_counts(), end="\n\n")

## 교차 검증:1
train 레이블 데이터 분포 : 
2    50
1    50
Name: label, dtype: int64
test 레이블 데이터 분포 : 
0    50
Name: label, dtype: int64

## 교차 검증:2
train 레이블 데이터 분포 : 
2    50
0    50
Name: label, dtype: int64
test 레이블 데이터 분포 : 
1    50
Name: label, dtype: int64

## 교차 검증:3
train 레이블 데이터 분포 : 
1    50
0    50
Name: label, dtype: int64
test 레이블 데이터 분포 : 
2    50
Name: label, dtype: int64



In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import numpy as np

skf = StratifiedKFold(n_splits=3)
n_iter = 0;
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
dt_clf = DecisionTreeClassifier()

features = iris.data
label = iris.target
accuracy_list = []

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter+=1
  x_train, x_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(x_train, y_train)
  pred = dt_clf.predict(x_test)

  accuracy_list.append(accuracy_score(y_test, pred))


print(accuracy_list)
print(np.mean(accuracy_list))

[0.98, 0.94, 0.98]
0.9666666666666667


In [ ]:
# kfold를 편하게 사용할 수 있도록 해주는 api : cross_val_score()
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris.data
label = iris.target

scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도 : ', np.round(scores,4))
print('교차 검증별 정확도 : ', np.round(np.mean(scores),4))


교차 검증별 정확도 :  [0.98 0.94 0.98]
교차 검증별 정확도 :  0.9667


In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

iris = load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=121, test_size=0.2)


dt_clf = DecisionTreeClassifier()

parameters = {"max_depth" : [1,2,3], "min_samples_split":[2,3]}

In [ ]:
import pandas as pd

grid_dtree = GridSearchCV(dt_clf, param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(x_train, y_train)

scores_df = pd.DataFrame(data=grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score", "split0_test_score", "split1_test_score", "split2_test_score"]]

params  ...  split2_test_score
0  {'max_depth': 1, 'min_samples_split': 2}  ...               0.70
1  {'max_depth': 1, 'min_samples_split': 3}  ...               0.70
2  {'max_depth': 2, 'min_samples_split': 2}  ...               0.95
3  {'max_depth': 2, 'min_samples_split': 3}  ...               0.95
4  {'max_depth': 3, 'min_samples_split': 2}  ...               0.95
5  {'max_depth': 3, 'min_samples_split': 3}  ...               0.95

[6 rows x 6 columns]

In [14]:
# data preprocessing
# label incoding
from sklearn.preprocessing import LabelEncoder
import numpy as np

encoder = LabelEncoder()
items = ['TV', "냉장고", "전자레인지","컴퓨터", "선풍기", "선풍기","믹서", "믹서"]

encoder.fit(items)
labels = encoder.transform(items)
print("encoder reuslt : ", labels)
test = [4,5,1,0,1,1,3,3]

print(type(labels))
test = encoder.inverse_transform(test)


print("inverse transform : ", test )

# one-hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder = LabelEncoder()
items = ['TV', "냉장고", "전자레인지","컴퓨터", "선풍기", "선풍기","믹서", "믹서"]

encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)


encoder = OneHotEncoder()
encoder.fit(labels)
result = encoder.transform(labels)
print(result.toarray())
print(result.shape)


encoder reuslt :  [0 1 4 5 3 3 2 2]
<class 'numpy.ndarray'>
inverse transform :  ['전자레인지' '컴퓨터' '냉장고' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(8, 6)
