<a href="https://colab.research.google.com/github/Tianea2160/PythonPractice/blob/master/tensorPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4]]

x_data = torch.tensor(data)

nd_array = np.array(data)


x_data = torch.from_numpy(nd_array)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
ones = torch.ones_like(x_data)
# shape는 유지하고 1로 tensor를 생성
print(ones)

rand = torch.rand_like(x_data, dtype=torch.float)
# shape는 유지하고 랜덤하게 tensor를 생성
print(rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.0682, 0.7551],
        [0.9429, 0.6905]])


In [ ]:
shape = (1,2,3)
ones = torch.ones(shape)

rands = torch.rand(shape)

zeros = torch.zeros(shape)

print(ones)
print(rands)
print(zeros)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[[0.6363, 0.2064, 0.3493],
         [0.6408, 0.6199, 0.0775]]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
# tensor attribute
shape = (3,4)
rand = torch.rand(shape)
print(rand.shape)
print(rand.dtype)
print(rand.device)

torch.Size([3, 4])
torch.float32
cpu


In [ ]:
shape = (3,4)
rand = torch.rand(shape)
print(rand.device)
# way to use cuda gpu
if torch.cuda.is_available():
  rand = rand.to("cuda")
print(rand.device)

cpu
cpu


In [ ]:
# slicing
shape = (3,4)
rand = torch.rand(shape)
print(rand)

print(rand[:, 2])
print(rand[:, 2].shape)
print(rand[:, :2])
print(rand[:, 2:])

tensor([[0.3908, 0.1059, 0.5848, 0.3131],
        [0.0015, 0.8538, 0.0948, 0.3279],
        [0.2169, 0.2775, 0.0318, 0.5617]])
tensor([0.5848, 0.0948, 0.0318])
torch.Size([3])
tensor([[0.3908, 0.1059],
        [0.0015, 0.8538],
        [0.2169, 0.2775]])
tensor([[0.5848, 0.3131],
        [0.0948, 0.3279],
        [0.0318, 0.5617]])


In [ ]:
tensor = torch.tensor([[1,2,],[3,4]])

print(torch.cat([tensor, tensor, tensor], dim=1))
print(torch.cat([tensor, tensor, tensor], dim=0))
# 2차원 텐서를 만들어서 사용하기 때문에 dim=1까지만 사용가능하다.(0,1)
# dim=2를 사용하려면 3차원 텐서를 선언해서 cat해야한다.

tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])
tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])


In [ ]:
tensor = torch.ones(3, 4)

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
print(tensor.T)
print(tensor)
print()
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
print(y3)

tensor = torch.ones(4, 4)
# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  if sys.path[0] == '':


In [ ]:
tensor = torch.rand(3,4)
print(tensor)
sum = tensor.sum()
print(sum)
print(tensor[1])
print(tensor[1].sum())

print(sum, type(sum))
sum_item = sum.item()
print(sum_item, type(sum_item))

tensor([[0.9469, 0.8758, 0.8034, 0.6910],
        [0.5362, 0.9458, 0.1100, 0.1789],
        [0.9823, 0.1922, 0.4550, 0.2152]])
tensor(6.9326)
tensor([0.5362, 0.9458, 0.1100, 0.1789])
tensor(1.7709)
tensor(6.9326) <class 'torch.Tensor'>
6.932648181915283 <class 'float'>


In [49]:
#inplace calculation
ones = torch.ones(3,4)
ones.add_(5)
print(ones)

# to numpy
np_data = ones.numpy()
print(np_data, type(np_data))

# 분명 tensor에 내용을 변경했는데 np_data의 정보도 같이 변경되는 것을 볼 수 있다. 리스트의 메모리를 래퍼런스 형태로 공유하는 것을 유추할 수 있다.
ones.add_(5)
print(np_data)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]] <class 'numpy.ndarray'>
[[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [11. 11. 11. 11.]]


In [50]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")
#np_data 변경사항이 tensor에도 영향을 끼치는 것을 볼 수 있다.

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
